project_id = "pkshffylgauatrcidqqj"

[functions.send-contract-email]
verify_jwt = false

[functions.send-test-email]
verify_jwt = false

[functions.send-booking-email]
verify_jwt = false

[functions.send-reminders]
verify_jwt = false

[functions.receive-reply]
verify_jwt = false

[functions.create-deposit-checkout]
verify_jwt = false

[functions.send-customer-email]
verify_jwt = false

[functions.send-deposit-request]
verify_jwt = false

[functions.notify-groomer]
verify_jwt = false

[functions.generate-campaign-email]
verify_jwt = false

[functions.send-campaign]
verify_jwt = false

[functions.handle-unsubscribe]
verify_jwt = false

[functions.send-scheduled-campaigns]
verify_jwt = false

[functions.sendgrid-webhook]
verify_jwt = false

[functions.send-sms]
verify_jwt = false

[functions.run-automations]
verify_jwt = false

[functions.pick-ab-winner]
verify_jwt = false

[functions.send-sms-reminders]
verify_jwt = false

[functions.receive-sms]
verify_jwt = false