ALTER TABLE public.error_reports 
ADD COLUMN IF NOT EXISTS plain_english TEXT,
ADD COLUMN IF NOT EXISTS impact TEXT,
ADD COLUMN IF NOT EXISTS severity TEXT DEFAULT 'medium',
ADD COLUMN IF NOT EXISTS fix_instruction TEXT,
ADD COLUMN IF NOT EXISTS lovable_prompt TEXT,
ADD COLUMN IF NOT EXISTS analysed_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS resolution_method TEXT;